# Generated by Django 5.0.6 on 2024-06-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_code_block',
            field=models.BooleanField(default=False),
        ),
    ]
