# Generated by Django 5.0.6 on 2024-06-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_has_code_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code_block',
            field=models.TextField(blank=True, null=True),
        ),
    ]
