# Generated by Django 5.0.6 on 2024-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_code_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='code_block',
        ),
        migrations.RemoveField(
            model_name='post',
            name='has_code_block',
        ),
    ]
